# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stakes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SlideMenuControllerSwift'
pod 'IQKeyboardManagerSwift'
pod 'EFCountingLabel'

pod 'Fabric'
pod 'Crashlytics'
pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

end
